run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = pattern for intentionally ignored errors
    exclude-functions:
      - (*os.File).Close  # Allow ignoring Close() errors for file handles

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: util/JSONReader.go
      linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"
