run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = pattern for intentionally ignored errors
    exclude-functions:
      - (io.Closer).Close  # Allow ignoring Close() errors in defers

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
